# filepath: manifests/applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/your-org/your-repo
        revision: main
        directories:
          - path: "microservices/*"
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/your-repo
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"